### PR TITLE
Add instance for ()

### PR DESCRIPTION
**Pull request by andrewthad**

### CODE REVIEW

**Comment by snoyberg** [comment]
What's the use case for this? My concern is that it may allow people to make mistakes. If there's a real world example where this would be useful, however, I have no objection.

**Comment by andrewthad** [comment]
I'm using this in a super sketchy library called yesod-crud-persist where I build CRUD subsites for models. If a model has no parent (example here, sort of: https://github.com/andrewthad/yesod-crud-persist/blob/master/src/Yesod/Crud/Simple.hs#L39), then the parent type is `()`. Otherwise, it will be `Key a)`, where `a` is the parent type. (It can also be `Maybe (Key c)` in the case of a hierarchy). But anyway, whatever it is, it has to have a `PathPiece` instance. I could just define my own data type:

    data NoParent = NoParent

But I figured I'd try getting in the instance for `()` first.

**Comment by snoyberg** [comment]
I'm OK with it, but wouldn't mind a second opinion. @gregwebs thoughts?

**Comment by gregwebs** [comment]
does it make more sense to use `()` instead of `_` ?

**Comment by snoyberg** [comment]
I'd guess not, as that makes for complicated URL escaping rules unnecessarily (not a problem for Yesod itself, but for users copy-pasting URLs elsewhere).

**Comment by andrewthad** [comment]
Sweet. Thanks.

**Pull request merged**
